### ISSUE TITLE
Support for Native TvOS

### ISSUE THREAD

**Issue by pranav-g10** [jwplayer/JWPlayer-iOS-SDK-cocoapod#24]
Currently attempting to use the pod in a TvOS project gives: `The platform of the target .... (tvOS 11.2) is not compatible with 'JWPlayer-SDK (2.8.1)', which does not support 'tvos'`. Similarly trying to use the Framework directly gives `Frameworks/JWPlayer_iOS_SDK.framework/JWPlayer_iOS_SDK: mach-o, but not built for tvOS simulator`

Is there any way to use the current pod/framework in a native TvOS app ? Are there any plans to add the support if doesn't exist ?

**Comment by karimJWP** [comment]
The iOS SDK is not meant to be used in the TVOS environment because we rely heavily on APIs that are not supported in TVOS. So far there are no plans on cross-compatibility. 
We did support an app builder for TVOS https://www.jwplayer.com/blog/jw-player-appletv-beta/ but it might be deprecated. For more info on that product please contact support+ott@jwplayer.com
